/**
 * Texts that threat collectors generate themselves (titles, distances, zone types),
 * in every interface language. Texts of official messages are passed on unchanged.
 */

const LABELS = {
  pl: {
    targetTypes: {
      uav: 'Dron (BSP)',
      shahed: 'Dron typu Shahed',
      fpv: 'Dron FPV',
      missile: 'Pocisk manewrujący',
      cruise: 'Pocisk manewrujący',
      ballistic: 'Pocisk balistyczny',
      kab: 'Bomba kierowana (KAB)',
      mig31k: 'MiG-31K (nosiciel Kinżała)',
      recon: 'Dron rozpoznawczy',
    },
    airObject: 'Obiekt powietrzny',
    confidence: { high: 'wysoka', medium: 'średnia', low: 'niska' },
    unknownConfidence: 'nieznana',
    kmFromYou: (km) => `${km} km od Ciebie`,
    towardsYou: 'kurs w Twoją stronę',
    confidenceLabel: (value) => `wiarygodność ${value}`,
    ukraine: 'Ukraina',
    zones: {
      TRA: 'strefa ćwiczeń',
      TSA: 'strefa wydzielona',
      D: 'strefa niebezpieczna',
      R: 'strefa ograniczeń',
      P: 'strefa zakazana',
      EA: 'strefa tymczasowa',
      MRT: 'trasa lotów wojskowych',
      ATZ: 'strefa lotniska',
    },
    airspaceZone: 'strefa przestrzeni powietrznej',
    activeZone: (zone, designator) => `Aktywna ${zone} ${designator}`,
    reservation: 'rezerwacja przestrzeni powietrznej',
    poland: 'Polska',
    wholeCountry: 'cała Polska',
    rsoMessage: 'Komunikat RSO',
    timeout: 'Przekroczono czas odpowiedzi',
    unavailable: 'Źródło niedostępne',
  },
  en: {
    targetTypes: {
      uav: 'Drone (UAV)',
      shahed: 'Shahed-type drone',
      fpv: 'FPV drone',
      missile: 'Cruise missile',
      cruise: 'Cruise missile',
      ballistic: 'Ballistic missile',
      kab: 'Guided bomb (KAB)',
      mig31k: 'MiG-31K (Kinzhal carrier)',
      recon: 'Reconnaissance drone',
    },
    airObject: 'Air object',
    confidence: { high: 'high', medium: 'medium', low: 'low' },
    unknownConfidence: 'unknown',
    kmFromYou: (km) => `${km} km from you`,
    towardsYou: 'heading towards you',
    confidenceLabel: (value) => `confidence ${value}`,
    ukraine: 'Ukraine',
    zones: {
      TRA: 'training area',
      TSA: 'segregated area',
      D: 'danger area',
      R: 'restricted area',
      P: 'prohibited area',
      EA: 'temporary area',
      MRT: 'military flight route',
      ATZ: 'aerodrome zone',
    },
    airspaceZone: 'airspace zone',
    activeZone: (zone, designator) => `Active ${zone} ${designator}`,
    reservation: 'airspace reservation',
    poland: 'Poland',
    wholeCountry: 'all of Poland',
    rsoMessage: 'RSO message',
    timeout: 'Response timed out',
    unavailable: 'Source unavailable',
  },
  uk: {
    targetTypes: {
      uav: 'Дрон (БпЛА)',
      shahed: 'Дрон типу «Шахед»',
      fpv: 'FPV-дрон',
      missile: 'Крилата ракета',
      cruise: 'Крилата ракета',
      ballistic: 'Балістична ракета',
      kab: 'Керована авіабомба (КАБ)',
      mig31k: 'МіГ-31К (носій «Кинджала»)',
      recon: 'Дрон-розвідник',
    },
    airObject: 'Повітряний об’єкт',
    confidence: { high: 'висока', medium: 'середня', low: 'низька' },
    unknownConfidence: 'невідома',
    kmFromYou: (km) => `${km} км від вас`,
    towardsYou: 'курс у ваш бік',
    confidenceLabel: (value) => `достовірність ${value}`,
    ukraine: 'Україна',
    zones: {
      TRA: 'навчальна зона',
      TSA: 'виділена зона',
      D: 'небезпечна зона',
      R: 'зона обмежень',
      P: 'заборонена зона',
      EA: 'тимчасова зона',
      MRT: 'маршрут військових польотів',
      ATZ: 'зона аеродрому',
    },
    airspaceZone: 'зона повітряного простору',
    activeZone: (zone, designator) => `Активна ${zone} ${designator}`,
    reservation: 'резервування повітряного простору',
    poland: 'Польща',
    wholeCountry: 'уся Польща',
    rsoMessage: 'Повідомлення RSO',
    timeout: 'Час очікування вичерпано',
    unavailable: 'Джерело недоступне',
  },
};

/** Supported language codes. */
export const LANGUAGES = Object.keys(LABELS);

/** Labels for a language; Polish for unknown codes. */
export function labelsFor(language) {
  return LABELS[language] || LABELS.pl;
}
